// declare module 'react-table';
declare module 'react-apexcharts';
declare module 'cleave.js';
declare module 'apexcharts';
declare module 'react-rating';
declare module 'google-maps-react';
// declare module '@react-jvectormap/core';
declare module 'react-dragula';
declare module 'react-dual-listbox';
// declare module 'react-data-table-component';
declare module 'react-table';